### ISSUE TITLE
evaluate() that gives an error in Matlab breaks the communication with the Matlab server

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/R.matlab#8]
Related to Issue #7, using `evaluate()` such that is results in an error on the Matlab server causes the communication with the Matlab server to stop working.

**The only solution seems to restart the Matlab server.**

# Example

In a fresh R session, start and connect to Matlab server (not show all Matlab output):

```r
> library("R.matlab")
> Matlab$startServer()
> matlab <- Matlab()
> open(matlab)
> matlab
[1] "Matlab: The MATLAB host is 'localhost' and communication goes via port 9999. Objects are passed via the local file system (remote=FALSE). The connection to the MATLAB server is opened."
```

Verify that the connection works:
```r
> evaluate(matlab, "1+1")
Received cmd: 1
"eval" string: "1+1"

ans =

     2

Sent byte: 0
```

Next, try to evaluate something that gives an error in Matlab:

```r
> evaluate(matlab, "y = 1+x")
Received cmd: 1
"eval" string: "y = 1+x"
EvaluationException:
Sent byte: -1
Error using java.io.DataOutputStream/writeUTF
Java exception occurred:
java.lang.NullPointerException
        at java.io.DataOutputStream.writeUTF(Unknown Source)
        at java.io.DataOutputStream.writeUTF(Unknown Source)

Error in MatlabServer (line 186)
      writeUTF(os, lasterr);

>> [2014-12-17 14:31:09] Exception: MatlabException:

  at #04. readResult.Matlab(this)
          - readResult.Matlab() is in environment 'R.matlab'

  at #03. readResult(this)
          - readResult() is in environment 'R.matlab'
          - originating from '<text>'

  at #02. evaluate.Matlab(matlab, "y = 1+x")
          - evaluate.Matlab() is in environment 'R.matlab'

  at #01. evaluate(matlab, "y = 1+x")
          - evaluate() is in environment 'R.matlab'

Error: MatlabException:
```

Not only does the request itself fails, it also breaks the state of the Matlab object 'matlab' causing it not to be able to communicate with the running Matlab server anymore.

```r
>  evaluate(matlab, "1+1")
Error in writeBin(con = con, as.integer(s), size = 2, endian = "big") :
  ignoring SIGPIPE signal
>
```

## Session information
```r
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-unknown-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] R.matlab_3.1.1

loaded via a namespace (and not attached):
[1] R.methodsS3_1.6.2 R.oo_1.18.2       R.utils_1.34.0    tools_3.1.2
```

**Comment by HenrikBengtsson** [comment]
This is probably because `lasterr` is null below. In other words, we need to assign an error message to `lasterr`.
```
    try 
      eval(bfr); 
      writeByte(os, 0);
      fprintf(1, 'Sent byte: %d\n', 0);
      flush(os);
    catch
      fprintf(1, 'EvaluationException: %s\n', lasterr);
      writeByte(os, -1);
      fprintf(1, 'Sent byte: %d\n', -1);
      writeUTF(os, lasterr);
      fprintf(1, 'Sent UTF: %s\n', lasterr);
      flush(os);
    end
```

**Comment by HenrikBengtsson** [comment]
Solved, cf. commit c6929e.
